# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ff71cecf-58b1-44f3-bf34-9f6ad03a80d8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ff71cecf-58b1-44f3-bf34-9f6ad03a80d8".device = "/dev/disk/by-uuid/ff71cecf-58b1-44f3-bf34-9f6ad03a80d8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6D03-CC49";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
