local M            = {}

M.border           = { "🭽", "▔", "🭾", "▕", "🭿", "▁", "🭼", "▏", }
M.border_telescope = { "▔", "▕", "▁", "▏", "🭽", "🭾", "🭿", "🭼", }

M.icons            = {
    diagnostics = {
        Error = " ",
        [vim.diagnostic.severity.ERROR] = " ",
        Warn = " ",
        [vim.diagnostic.severity.WARN] = " ",
        Hint = " ",
        [vim.diagnostic.severity.HINT] = " ",
        Info = " ",
        [vim.diagnostic.severity.INFO] = " ",
    },
    git = {
        added = " ",
        branch = " ",
        conflict = " ",
        deleted = " ",
        ignored = "⍟",
        modified = " ",
        removed = " ",
        renamed = "➜ ",
        staged = "✓ ",
        unstaged = "✗ ",
        untracked = "★ ",
    },
    filesystem = {
        empty_folder = " ",
        open_folder = " ",
        folder = " ",
        file = " ",
        link = " ",

    },
    tree = {
        expander_collapsed = "",
        expander_expanded = "",
        indent_marker = "│",
        last_indent_marker = "└",
    },
    debugging = {
        breakpoint = "",
        breakpoint_conditional = "",
        breakpoint_rejected = "",
        logpoint = "",
        current_position = " ",
        disconnect = " ",
        pause = " ",
        play = " ",
        run_last = " ",
        step_back = " ",
        step_into = " ",
        step_out = " ",
        step_over = " ",
        terminate = " ",
    },
    kinds = {
        Array = " ",
        Boolean = " ",
        Class = " ",
        Color = " ",
        Constant = " ",
        Constructor = " ",
        Copilot = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = " ",
        Function = " ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = " ",
        Module = " ",
        Namespace = " ",
        Null = " ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = " ",
    },
}

return M
